version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: sms_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-sponsorship_db}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sms_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sms_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    networks:
      - sms_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sms_frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - sms_net

volumes:
  db_data:

networks:
  sms_net:
    driver: bridge
